### PR TITLE
fix: Update file-collections to fix product image upload

### PR DESCRIPTION
**Pull request by focusaurus**
- Clean up package-lock via npm install to correctly
  use the public npm registry
- Part of reactioncommerce/reaction issue 6298

Impact: **minor**
Type: **bugfix**

## Issue

Uploading product images was failing.

## Solution

See https://github.com/reactioncommerce/reaction/issues/6298 for details. The fix will have to flow through several repos:

- reactioncommerce/file-collections (fixed in v0.9.3)
- reactioncommerce/file-collections-sa-gridfs (fixed in v0.1.4)
- reactioncommerce/api-plugin-files (this repo)
- reactioncommerce/docker-base (tangential)
- reactioncommerce/reaction

## Breaking changes

None known.

## Testing

- In reaction admin, create a product, save it, then upload an image. If it succeeds and the thumbnail is visible, this fix is verified.

### CODE REVIEW

**Comment by willopez** [comment]
@focusaurus DOC issue

**Comment by focusaurus** [comment]
Can you tell what specifically? The commit is signed off. shrug.

**Comment by willopez** [comment]
You are right, it is signed off, I just set it to pass manually.

**Review by willopez — APPROVED** [review]
LGTM

**Pull request merged**
